### ISSUE TITLE
GraphiQL can not explore schema

### ISSUE THREAD

**Issue by aguiraf** [conveyal/gtfs-api#17]
this is mainly because GraphiQL expects the response to the IntrospectionQuery to be wrapped inside a "data" entry.
Actually any successful GraphQL response should always have the  "data" field as first entry, as defined by the spec http://facebook.github.io/graphql/October2016/#sec-Response-Format
I'm proposing a little PR to address GraphiQL needs for the schema, but you might consider the possibility to refactor the api and the clients to always wrap successful responses in a "data" entry...

**Comment by abyrd** [comment]
Hi @aguiraf, thanks for pointing this out. As `gtfs-api` is no longer maintained (having been integrated into gtfs-lib) the appropriate tickets are now 
GraphQL responses structured wrong conveyal/gtfs-lib#94
 Open
Fix graphql specification catalogueglobal/datatools-server#68
